name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change to master if your default branch is named master

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Format Commit Date
        id: get_date
        run: |
          # Fetch the date from the commit log
          RAW_DATE=$(git log -1 --format=%cd --date=format:'%b. %-d, %Y %H:%M:%S')
          
          # Convert to lowercase letters
          FORMATTED_DATE=$(echo "$RAW_DATE" | tr '[:upper:]' '[:lower:]')
          
          # Save it as an environment variable
          echo "commit_date=$FORMATTED_DATE" >> $GITHUB_ENV

      - name: Inject Commit Data into HTML
        run: |
          # Use a temporary file path to guarantee Linux updates the stream correctly
          sed "s/COMMIT_DATE_PLACEHOLDER/${{ env.commit_date }}/g" index.html > temp.html && mv temp.html index.html
          sed "s/LATEST_COMMIT_SHA/${{ github.sha }}/g" index.html > temp.html && mv temp.html index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
